import React from 'react';

interface ReviewOutputProps {
  feedback: string;
  isLoading: boolean;
}

export const ReviewOutput: React.FC<ReviewOutputProps> = ({ feedback, isLoading }) => {
  if (isLoading) {
    return (
      <div className="h-full flex items-center justify-center space-y-4 flex-col">
        <div className="loading-gear animate-gear-rotate"></div>
        <p className="text-copper-green font-fallout-pixel text-sm terminal-text animate-flicker">
          AI ANALYSIS IN PROGRESS...
        </p>
        <div className="flex space-x-1">
          <div className="w-2 h-2 bg-copper-green rounded-full animate-pulse"></div>
          <div className="w-2 h-2 bg-copper-green rounded-full animate-pulse" style={{ animationDelay: '0.2s' }}></div>
          <div className="w-2 h-2 bg-copper-green rounded-full animate-pulse" style={{ animationDelay: '0.4s' }}></div>
        </div>
      </div>
    );
  }

  if (!feedback) {
    return (
      <div className="h-full flex items-center justify-center flex-col space-y-4">
        <div className="text-center">
          <pre className="font-fallout-pixel text-copper-green text-xs leading-none terminal-text opacity-50">
{`    ____
   /    \\
  |  ()  |
   \\____/
   READY`}
          </pre>
        </div>
        <p className="text-copper-green font-fallout-mono text-lg terminal-text">
          AWAITING CODE INPUT...
        </p>
        <p className="text-fallout-tan text-sm font-fallout-mono opacity-70 text-center max-w-md">
          Submit your code for comprehensive analysis by our advanced AI systems. 
          Quality assured by Vault-Tec Industries.
        </p>
      </div>
    );
  }

  return (
    <div className="h-full overflow-y-auto">
      <div className="mb-4 pb-2 border-b border-copper-green">
        <div className="flex items-center justify-between">
          <h3 className="text-warning-yellow font-fallout-heading font-bold text-lg terminal-text">
            ANALYSIS REPORT
          </h3>
          <div className="flex items-center space-x-2">
            <div className="w-2 h-2 bg-screen-green rounded-full"></div>
            <span className="text-screen-green font-fallout-pixel text-xs">
              COMPLETE
            </span>
          </div>
        </div>
      </div>
      
      <div className="prose prose-invert max-w-none">
        <pre className="whitespace-pre-wrap font-fallout-mono text-sm leading-relaxed text-fallout-tan terminal-text">
          {feedback}
        </pre>
      </div>
      
      {/* Footer info */}
      <div className="mt-6 pt-4 border-t border-copper-green opacity-50">
        <p className="text-xs font-fallout-pixel text-center text-copper-green">
          Report generated by Vault-Tec AI Systems v2.1.7
        </p>
      </div>
    </div>
  );
};